### PR TITLE
Add more information to the result page

### PR DESCRIPTION
**Pull request by hazrpg**
I have added more information to the displayed results:
 * Add tooltips (in the form of html attr title) to explain the badges.
 * Add number of answers available for a question.
 * Add a check mark to outline if the question has an accepted answer or not.
 * Add a check mark to outline which answer has been accepted.
 * Add credits of who asked the question next to the date (with link back to profile).
 * Add credits of who answered the question (with link back to profile) and the date they answered it on the answer tab.
 * Add new CSS rules for the new elements (as mentioned above).
 * Update the existing CSS rules to better reflect the information presented.

Please see attached screenshots:

### CODE REVIEW

**Comment by hazrpg** [comment]
Just thought I would point out that the errors in the failed build above is not due to the code I have added.

**Comment by Chris911** [comment]
Thanks for your contributions @hazrpg. I'll review tomorrow. 

As for CI I know it's broken. Haven't had time to fix the tests.

**Comment by hazrpg** [comment]
You're welcome @Chris911, I hope you like the changes. If there is anything you don't like in the changes, let me know and I'll amend it accordingly.

If I get chance, I might have a go at fixing the tests.

**Comment by Chris911** [comment]
Looks good @hazrpg except I can't get the tooltips to work here. Also can't figure out how they're supposed to work by looking at the code there's no `hover` css class or anything like that.

**Comment by hazrpg** [comment]
Thanks @Chris911, glad you like it. I wanted to keep it simple, so I used traditional tooltips using the "title" attribute. They don't appear instantly, they take a couple of seconds to appear after hovering over it.

For example on line 72 of `lib/ask-stack-result-view.coffee`:

    @p class: 'icon icon-check', title: 'This question has an accepted answer' if question['accepted_answer_id']

**Comment by Chris911** [comment]
@hazrpg yep it works. My bad for being impatient :stuck_out_tongue_closed_eyes:. 

Everything looks good. I'll merge this tonight and create a release. 

Thanks for your contribution! Might be time to refactor the code a little bit and fix some bugs.

**Comment by hazrpg** [comment]
@Chris911, I wish I had seen your reply sooner. I genuinely thought it was a bug, so I set out to change it to a CSS version. If you're happy with the original implementation I did, then I'm happy to roll my commit back.

Here's a screenshot of the CSS implementation:
screenshot from 2016-01-26 01 53 02
screenshot from 2016-01-26 01 53 51

**Comment by Chris911** [comment]
These tooltips look good as well. Go for another PR when you're happy with the result.

**Comment by Chris911** [comment]
Release 2.1.0 includes this change.

**Comment by hazrpg** [comment]
Excellent, thanks for adding it into the release. Hopefully others will like the change too. :smiley:

**Pull request merged**
